name: Scrape for Citation Data

on:
  push:
    branches: ['main']
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Install NPM Stufff
      run: npm install --save request request-promise cheerio puppeteer
    - name: Run Scraper
      run: node scraper.js
    - name: Commit files
      run: |
        git config --local user.name "Github Action"
        git add citation_stats.json
        git commit -m "Updated Citation Data"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
